resources:
  - all.yaml
  
patches:
- target:
    kind: Deployment
    labelSelector: "app.kubernetes.io/name=bxhealthapp"
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: deploy
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 0
            runAsUser: 0
            runAsGroup: 0
