# This file only contains values that should be different in a dev environment
ping-devops:
  global:
    ingress:
      addReleaseNameToHost: append
      defaultDomain: ping-devops.com
      defaultTlsSecret:
      annotations:
        # nginx example
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        kubernetes.io/ingress.class: "nginx-public"
  pingaccess-admin:
    ingress:
      enabled: true
    envs:
      SERVER_PROFILE_ADMIN_BRANCH: "${SERVER_PROFILE_BRANCH}"
      SERVER_PROFILE_BRANCH: "${SERVER_PROFILE_BRANCH}"

  pingaccess-engine:
    envs:
      SERVER_PROFILE_BRANCH: "${SERVER_PROFILE_BRANCH}"

  pingfederate-admin:
    ingress:
      enabled: true
    envs:
      SERVER_PROFILE_ADMIN_BRANCH: "${SERVER_PROFILE_BRANCH}"
      SERVER_PROFILE_BRANCH: "${SERVER_PROFILE_BRANCH}"

  pingfederate-engine:
    envs:
      SERVER_PROFILE_BRANCH: "${SERVER_PROFILE_BRANCH}"

  pingdirectory:
    envs:
      SERVER_PROFILE_BRANCH: "${SERVER_PROFILE_BRANCH}"

  pingdataconsole:
    ingress:
      enabled: true
    enabled: true
    envs:
      SERVER_PROFILE_PATH: profiles/pingdataconsole
      PDC_PROFILE_SHA: "${PINGDATACONSOLE_SHA}"
      SERVER_PROFILE_BRANCH: "${SERVER_PROFILE_BRANCH}"
      SERVER_PROFILE_URL: "https://github.com/${GITHUB_REPOSITORY}"

  pingauthorize:
    ingress:
      enabled: true
    enabled: true
    envs:
      SERVER_PROFILE_BRANCH: "${SERVER_PROFILE_BRANCH}"